### ISSUE TITLE
Just a little question.

### ISSUE THREAD

**Issue by MadRatSRP** [netguru/Kissme#39]
Hello, your project looks awesome, thanks for your job! I would like to know is there any ability to rename the name of the storage after i'll set it up? Thanks.

**Comment by samiuelson** [comment]
Hey @MadRatSRP 
There is no explicit API for storage rename operation. You can create new storage instance with the new name and copy data from the previous one.

**Comment by MadRatSRP** [comment]
Thanks, and one more question. Should i add binaryprefs lib to the project to make your code work? Cause im getting this error:
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ironz/binaryprefs/BinaryPreferencesBuilder;
        at com.netguru.kissme.EncryptionKeysStorage.getKey$android_release(EncryptionKeysStorage.kt:32)
        at com.netguru.kissme.AndroidStorageProvider.preferences$android_release(AndroidStorageProvider.kt:35)
        at com.netguru.kissme.Kissme$preferences$2.invoke(Kissme.kt:15)
        at com.netguru.kissme.Kissme$preferences$2.invoke(Kissme.kt:12)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.netguru.kissme.Kissme.getPreferences(Unknown Source:7)
        at com.netguru.kissme.Kissme.putInt(Kissme.kt:26)
        at com.madrat.abiturhelper.ui.standard.StandardView$onActivityCreated$1.onClick(StandardView.kt:39)
        at android.view.View.performClick(View.java:6304)
        at android.view.View$PerformClick.run(View.java:24803)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6606)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ironz.binaryprefs.BinaryPreferencesBuilder" on path: DexPathList[[zip file "/data/app/com.madrat.abiturhelper-ztH_v9mdm2qb4c0E2eOT6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.madrat.abiturhelper-ztH_v9mdm2qb4c0E2eOT6A==/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)`

**Comment by samiuelson** [comment]
@MadRatSRP Binaryprefs should be already bundled into the Kissme Android artifact in the latest release version 0.2.1.  

In 0.2.0 it was required to add Binaryprefs as a separate Android dependency.

**Comment by MadRatSRP** [comment]
Thank you again =)

**Comment by MadRatSRP** [comment]
Its strange, but im still getting this error even after updating it to the 0.2.1. May you check it by yourself once again please?

**Comment by samiuelson** [comment]
@MadRatSRP We've just merged a fix for the issue with `kissme-android` artifact .pom file missing dependencies declarations. 

Please test the latest Kissme 0.2.3 release. The binaryprefs should be resolved now automatically.

Note that `maven { url "https://jitpack.io" }` repo must be added to the project in order to allow to resolve binaryprefs automatically. You can refer to the instructions in Readme.md.

**Comment by MadRatSRP** [comment]
Its working now, thanks for your reply! If its not a big challenge, please think about adding opportunity to rename existing storage just like storage.rename("new_name"). 
And thanks again for your library, its way handier than Bundle and i''ll definitely use it again and again! Have a nice day =)

**Comment by samiuelson** [comment]
Thanks for submitting the issue and testing the lib 👍I'm marking the issue as resolved then

**Comment by samiuelson** [comment]
@MadRatSRP What would be your use case for calling `storage.rename("new_name")`?

**Comment by freszu** [comment]
@MadRatSRP well maybe it would then make sense to instead use some unique id to identify user - you wouldn't have to rename anything in any case and would be sure that given id always represents given user as login/nickname can be changed at anytime - this would especially make sense if you want to keep it in sync with backend which definitely should be using some sort of id as primary key  😉
